[project]
# Refer to: https://docs.chainlit.io/backend/config/project
# Whether to enable telemetry (default: true). No personal data is collected.
enable_telemetry = true

# List of environment variables to be provided by each user to use the app.
user_env = []

# Duration (in seconds) during which the session is saved when the connection is lost
session_timeout = 3600

# Enable third parties caching (e.g LangChain cache)
cache = false

# Authorized origins
allow_origins = ["*"]

# Follow symlink for asset mount (see https://github.com/Chainlit/chainlit/issues/317)
# follow_symlink = false

[features]
# Show the prompt playground
prompt_playground = true

# Process and display HTML in messages. This can be a security risk (see https://stackoverflow.com/questions/19603097/why-is-it-dangerous-to-render-user-generated-html-or-javascript)
unsafe_allow_html = false

# Process and display mathematical expressions. This can clash with "$" characters in messages.
latex = false

# Automatically tag threads with the current chat profile (if a chat profile is used)
auto_tag_thread = true

# Authorize users to upload files with messages
[features.multi_modal]
    enabled = true
    accept = ["*/*"]
    max_files = 20
    max_size_mb = 500

# Allows user to use speech to text
[features.speech_to_text]
    enabled = false
    # See all languages here https://github.com/JamesBrill/react-speech-recognition/blob/HEAD/docs/API.md#language-string
     language = "en-US"

[UI]
# Name of the app and chatbot.
name = "Home AI | Multi-provider LLM Chat app built with Chainlit"

# Show the readme while the thread is empty.
show_readme_as_default = false

# Description of the app and chatbot. This is used for HTML tags.
description = "A Chainlit chat app that supports multiple profiles with various chat providers including CHatGPT, Claude and Gemini"

# Large size content are by default collapsed for a cleaner ui
default_collapse_content = true

# The default value for the expand messages settings.
default_expand_messages = false

# Hide the chain of thought details from the user in the UI.
hide_cot = false

# Link to your github repo. This will add a github button in the UI's header.
 github = "https://github.com/mungana-ai/homeai.git"

# Specify a CSS file that can be used to customize the user interface.
# The CSS file can be served from the public directory or via an external link.
# custom_css = "/public/test.css"

# Specify a Javascript file that can be used to customize the user interface.
# The Javascript file can be served from the public directory.
# custom_js = "/public/test.js"

# Specify a custom font url.
# custom_font = "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap"

# Specify a custom build directory for the frontend.
# This can be used to customize the frontend code.
# Be careful: If this is a relative path, it should not start with a slash.
# custom_build = "./public/build"

# Override default MUI light theme. (Check theme.ts)
[UI.theme]
    font_family = "Inter, sans-serif"

[UI.theme.light]
    background = "#F0F8F7"
    paper = "#FFFFFF"

    [UI.theme.light.primary]
        main = "#4CAF50"
        dark = "#357A38"
        light = "#C8E6C9"

[UI.theme.dark]
    background = "#263238"
    paper = "#37474F"

    [UI.theme.dark.primary]
        main = "#66BB6A"
        dark = "#388E3C"
        light = "#B9F6C"

[meta]
generated_by = "1.0.506"
